export default [
  {
    id: 'a1',
    top: '9px',
    left: '11px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'a2',
    top: '9px',
    left: '125px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'a3',
    top: '9px',
    left: '239px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'a4',
    top: '9px',
    left: '354px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'a5',
    top: '9px',
    left: '468px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'a6',
    top: '9px',
    left: '582px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'b1',
    top: '123px',
    left: '11px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'b2',
    top: '123px',
    left: '126px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'b3',
    top: '123px',
    left: '240px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'b4',
    top: '123px',
    left: '354px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'b5',
    top: '123px',
    left: '468px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'b6',
    top: '123px',
    left: '582px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'c1',
    top: '238px',
    left: '12px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'c2',
    top: '238px',
    left: '126px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'c3',
    top: '238px',
    left: '240px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'c4',
    top: '238px',
    left: '354px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'c5',
    top: '238px',
    left: '468px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
  {
    id: 'c6',
    top: '237px',
    left: '582px',
    type: 0,
    backgroundImage: null,
    uniqueCode: 0,
    dragOver: false,
    queue: 0,
    level: 0,
  },
];
